# wrangler.toml
compatibility_date = "2025-09-15"
name = "speedtest"
type = "webpack"
account_id = "" # You can leave this blank or add your Cloudflare account ID
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./dist"
entry-point = "workers-site/index.js"

